# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. 
on:
  schedule:
    - cron: "0 4 * * 1"
  push:
    branches: [ main ] 
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        repository: planemo-autoupdate/galaxytools
        ref: master
        
    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    # Download github cli
    - name: Download github cli
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh
        
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo "Setting up virtual env..."
        pip3 install wheel
        sudo pip3 install virtualenv
        virtualenv .au
        source .au/bin/activate
        #pip install conda
        
        echo "Installing planemo..."
        pip install https://github.com/simonbray/planemo/archive/autoupdate-sb.zip  # install from Simon's fork for now
        #planemo --help
        planemo conda_init
        # git credentials
        git config --global user.email "sbray@informatik.uni-freiburg.de"
        git config --global user.name "planemo-autoupdate"
        echo "Adding upstream..."
        git remote add upstream https://github.com/simonbray/galaxytools.git
        echo "Getting git remote"
        git remote -v
        echo "Pulling latest from upstream"
        git pull upstream master --allow-unrelated-histories
        #git pull origin master
        #cd chemicaltoolbox/sucos
        echo "Current directory is:"
        pwd
        echo "Running autoupdate command..."
        planemo autoupdate -r
        git status
        echo "Adding..."
        git add .
        echo "Committing..."
        git commit -m "Version Update"
        #echo "Authenticating..."
        echo ${{ secrets.PAT }} > token.txt
        gh auth login --with-token < token.txt
        echo "Pushing..."
        #git push https://$GITHUB_ACTOR:${{ secrets.PAT }}@github.com/$GITHUB_ACTOR/galaxytools.git master
        echo "Creating a PR..."
        gh pr create --head planemo-autoupdate:master --title "Version Update" --body "XYZ" --repo simonbray/galaxytools